Vagrant.configure('2') do |config|
  config.vm.box = 'bento/centos-7.1'
  config.vm.hostname = 'centos.box'
  config.vm.network :private_network, ip: '192.168.199.90'
  config.vm.provider :virtualbox do |vb|
    vb.customize [
      'modifyvm', :id,
      '--cpuexecutioncap', '50',
      '--memory', '512'
    ]
  end
end
